class Settings():
    RESERVATION_OPEN_HOUR = 22
    RESERVATION_LIMIT_PER_DAY = 6
    RESERVATION_LIMIT_PER_ROOM = 3
    BOARD_MAX_TITLE_LENGTH = 30
    BOARD_MAX_CONTENT_LENGTH = 300
    COMMENT_MAX_CONTENT_LENGTH = 300

    def to_dict(self):
        return {
            "RESERVATION_OPEN_HOUR" : self.RESERVATION_OPEN_HOUR,
            "RESERVATION_LIMIT_PER_DAY" : self.RESERVATION_LIMIT_PER_DAY,
            "RESERVATION_LIMIT_PER_ROOM" : self.RESERVATION_LIMIT_PER_ROOM,
            "BOARD_MAX_TITLE_LENGTH" : self.BOARD_MAX_TITLE_LENGTH,
            "BOARD_MAX_CONTENT_LENGTH" : self.BOARD_MAX_CONTENT_LENGTH,
            "COMMENT_MAX_CONTENT_LENGTH" : self.COMMENT_MAX_CONTENT_LENGTH
        }