"""Initial migration.

Revision ID: a76e4200e3c0
Revises: 
Create Date: 2024-12-23 09:37:19.048280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76e4200e3c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('room_id', sa.String(length=20), nullable=False),
    sa.Column('room_number', sa.String(length=10), nullable=False),
    sa.Column('room_name', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'MAINTENANCE', 'OCCUPIED', 'CLOSED', name='roomstatus'), nullable=False),
    sa.PrimaryKeyConstraint('room_id'),
    sa.UniqueConstraint('room_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room')
    # ### end Alembic commands ###
